{{- $fullName := include "test-01.fullname" . -}}
{{- range .Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: ns-{{ .component }}-{{ $fullName }}
  name: svc-{{ .component }}
spec:
  selector:
    app: {{ .component }}
  ports:
    {{- range .ports }}
    - name: {{ .proto | lower}}-{{ .port }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
{{- end }}

