---
- name: install common k8s packages
  hosts: k8s
  become: yes
  roles:
    - k8s-common

- name: setup master-nodes
  hosts: master
  become: yes
  roles: 
    - k8s-master

- name: setup worker-nodes
  hosts: worker
  become: yes
  roles: 
    - k8s-worker