---
# Source: test-01/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ns-web-chart-1700128947-test-01
  labels:
    app: web
apiVersion: v1
kind: Namespace
metadata:
  name: ns-app-chart-1700128947-test-01
  labels:
    app: app
apiVersion: v1
kind: Namespace
metadata:
  name: ns-db-chart-1700128947-test-01
  labels:
    app: db
---
# Source: test-01/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: ns-web-chart-1700128947-test-01
  name: svc-web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
apiVersion: v1
kind: Service
metadata:
  namespace: ns-app-chart-1700128947-test-01
  name: svc-app
spec:
  selector:
    app: app
  ports:
    - port: 9000
      targetPort: 9000
apiVersion: v1
kind: Service
metadata:
  namespace: ns-db-chart-1700128947-test-01
  name: svc-db
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
---
# Source: test-01/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-web-chart-1700128947-test-01
  name: dl-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: cnt-web
          image: nginx
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 30m
              memory: 50Mi
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-app-chart-1700128947-test-01
  name: dl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: cnt-app
          image: php:8.2-fpm
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 30m
              memory: 50Mi
          ports:
          - containerPort: 9000
            protocol: TCP
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-db-chart-1700128947-test-01
  name: dl-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: cnt-db
          image: postgres
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 30m
              memory: 150Mi
          ports:
          - containerPort: 5432
            protocol: TCP
---
# Source: test-01/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ns-web-chart-1700128947-test-01
  name: ing-web
spec:
  ingressClassName: nginx
  rules:
    - host: test.local
      http:
        paths:
          - path: /
            backend:
              service:
                name: svc-web
                port:
                  number: 80
status:
  loadBalancer:
    ingress:
      - ip: 192.168.122.139
